name: Dockyman build/push base image(s)

on:
  release:
    types:
      - created
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
         
      - name: Build and push Docker image
        run: |
          make -C .dockyman development
          make -C .dockyman build          
